### PR TITLE
Fix dependency cycle in transpiled code

### PR DESCRIPTION
**Pull request by dslmeinte**
fixes issue #81

### CODE REVIEW

**Comment by lazka** [comment]
I can confirm that rollup no longer warns with this branch and my tests using certlogic-js are green.

Thanks!

**Comment by dslmeinte** [comment]
@lazka Could you also check whether the updated NPM package works for you? (It has not only the fix for the circular dep, but I cleaned it up a bit better as well.)

**Comment by lazka** [comment]
looks all good here

**Comment by dslmeinte** [comment]
Hi @lazka , Thanks for checking!

**Pull request merged**
