### PR TITLE
implement validator in Kotlin + fix some other stuff

### PR DESCRIPTION
**Pull request by dslmeinte**
(is also issue #39)

### CODE REVIEW

**Comment by dslmeinte** [comment]
@ggrund-tsi Hi Gordon, Are you able to review this? Or are you on (well-deserved) holidays?

**Comment by dslmeinte** [comment]
@ikbendewilliam Could I maybe entice you to have a quick look at this PR, and especially the small change to the Dart implementation?

**Comment by ikbendewilliam** [comment]
@dslmeinte Change looks good 👍 Tests run fine. I'll publish version 0.0.5 once I fix the reduce

**Review by ikbendewilliam — APPROVED** [review]
✅ Dart

**Pull request merged**
