### PR TITLE
Extract from UVCI-operation

### PR DESCRIPTION
**Pull request by dslmeinte**

### CODE REVIEW

**Comment by oleksandrsarapulovgl** [comment]
Hi @dslmeinte ! Thank you very much for the changes.

Is there a chance you could merge it and prepare new jar library release?

**Comment by dslmeinte** [comment]
@oleksandrsarapulovgl Glad you like it! I've asked the original requestor(s) to review it so I can merge it. If you like to review it: please add yourself as a reviewer.

As soon as I've merged it I'll make a new Kotlin release as well.

**Comment by oleksandrsarapulovgl** [comment]
I'm not sure I'm the right person to review this. Who typically should review this?

**Comment by dslmeinte** [comment]
@oleksandrsarapulovgl Either someone from T-Systems, or the person from IBM working with them. Are you working at/for T-Systems as well?

**Comment by oleksandrsarapulovgl** [comment]
Yes, but I'm not the right person to review this

**Comment by dslmeinte** [comment]
@oleksandrsarapulovgl Understood. Maybe you can nudge AlCi from IBM, or MaMi (or @ggrund-tsi or @SchulzeStTSI) from T-Systems a bit about this?

**Review by oleksandrsarapulovgl — APPROVED** [review]

**Comment by dslmeinte** [comment]
@oleksandrsarapulovgl Thanks for reviewing and approving!

**Pull request merged**
