### PR TITLE
Feature/dart trim data parameter

### PR DESCRIPTION
**Pull request by ikbendewilliam**
Added a trimData parameter to the evaluate function
The reason for this is that there are certificates where the vaccination isn't correctly defined. We've been asked to still allow these. The current solution is to have this in our ruleset:
```json
  "in": [
    {
      "var": "payload.v.0.mp"
    },
    [
      "EU/1/20/1528",
      "EU/1/20/1528 ",
      "EU/1/20/1507",
      "EU/1/20/1507 ",
...
    ]
  ]
```

### CODE REVIEW

**Comment by dslmeinte** [comment]
I'm a little bit on the fence about this. I definitely understand the problem, but I'm not sure it's a good idea to solve this in this way within CertLogic. I'd like to keep the implementations of CertLogic in JS, Kotlin, Dart, Swift, etc. as equivalent as possible, which would mean this would have to be ported to JS, Kotlin, Swift, etc. as well.

It seems that trimming everything is a bit heavy-handed: it basically means that equality of strings is re-defined module trimming whitespace off of either end. In general, I'm not in favour of this kind of “magic” semantics.

Can I suggest another solution: pre-process the JSON payload of DCCs beforehand, trimming the fields for which it's known that they may be problematic, such as `v.0.mp`?

**Comment by ikbendewilliam** [comment]
Yes, I'm not the biggest fan of this either (that's why this is a separate PR). I did it this way for 2 reasons.
1. People that use our package may not be aware that the issue exists
2. There may be more similar issues that we are not aware of
So we can do the solution you suggest, make it a separate method that fixes the v.0.mp and write it clear in the docs of our package that we recommend using it.
If we ever find any issue like it, I'll add that to the method. Not that I expect this to occur again.

**Comment by ikbendewilliam** [comment]
After discussing it, we'll put it internally so the package stays the same across platforms 👍

**Comment by dslmeinte** [comment]
I'm glad you agree with my arguments, @ikbendewilliam . I now remember I had the same discussion with our DE counterparts, and they ended up doing the same thing (data cleaning prior to business rule evaluation).

AFAICS, the changes to https://github.com/ehn-dcc-development/dgc-business-rules/pull/100/files#diff-ec833e82cf57cbb2017557cf81f0866be54d217186542ba6fcd93125a7dd81ec are unrelated to trimming, so you might want to make that the subject of a separate, new PR?

In any case: thanks for contributing so much to this repository, especially the Dart implementation!

**Comment by ikbendewilliam** [comment]
Yes, the changes you mention are to support a testSuite that is not shared. I don't think it will be necessary if we want to keep the packages in line. There are a few other changes that I'll be taking over before releasing a new version.

No problem 😄

**Comment by dslmeinte** [comment]
@ikbendewilliam We're cleaning up the eHN repos. Can we delete this branch?

**Comment by ikbendewilliam** [comment]
Ah yes, this can indeed be deleted 👍

**Comment by dslmeinte** [comment]
Thanks, @ikbendewilliam, for contributing your Dart implementation to this project! 🙇‍♂️

**Comment by ikbendewilliam** [comment]
You're welcome, you know where to find me if you need some more dart 😉

**Pull request closed without merging**
